default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Singapore2018# #<-- which you have defiend while installing postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: simple_web_development

test:
  <<: *default
  database: simple_web_test

production:
  <<: *default
  database: simple_web_production
  username: username
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>